# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build my-lab`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t my-lab`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system my-lab && \
          adduser --system -G my-lab my-lab

COPY dist/my-lab my-lab
RUN chown -R my-lab:my-lab .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix my-lab --omit=dev -f install

CMD [ "node", "my-lab" ]
